### ISSUE TITLE
TwinCAT Project referenced but not present

### ISSUE THREAD

**Issue by ZacharyDaulton** [ollzer/TwinCAT-HMI-Samples#1]
The VS solution file references the following on lines 8 and 9

Project("{B1E792BE-AA5F-4E3C-8C82-674BF9C0715B}") = "TwinCAT PLC HMI", "..\..\_Trainings\2018-09-19 HMI\TwinCAT PLC HMI\TwinCAT PLC HMI\TwinCAT PLC HMI.tsproj", "{86B803FA-A3A4-4E75-9A4D-B6E329A97C38}"
EndProject

The .tsproj is not present within this repository though and presents an error on loading. 
"error  : The project file or web has been moved, renamed or is not on your computer."

**Comment by ollzer** [comment]
Fixed in commit: https://github.com/ollzer/TwinCAT-HMI-Samples/commit/058040d19184eb49842792ec612bbd94f70743f2
